name: megatour_app
description: "Mega travel flutter app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Network & API
  http: ^1.1.0
  dio: ^5.4.0

  # State Management
  provider: ^6.1.1

  # Local Storage
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.0.0

  # Navigation
  go_router: ^12.1.3

  # JSON Serialization
  json_annotation: ^4.8.1

  # UI Components
  cached_network_image: ^3.4.1
  flutter_rating_bar: ^4.0.1
  intl: ^0.19.0
  webview_flutter: ^4.7.0
  lottie: ^3.1.0

  # Utils
  fluttertoast: ^8.2.4
  loading_animation_widget: ^1.2.0
  flutter_widget_from_html: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1
  device_info_plus: ^9.1.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icon/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"
